MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001  # 0.0001 per image instead of 0.00125
  GAMMA: 0.1
  MAX_ITER: 240000 # finetune schedule, 1/6 th of a full training schedule on coco.
  STEPS: [0, 160000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  DOMAIN_ADAPTATION: True
  DA_IMG_GRL_WEIGHT: 0.2
  DA_INS_GRL_WEIGHT: 0.6 # PADA, save me.
  PADA: True
  DA_FADE_IN: True
  DA_LR_MULT: 10
  WEIGHTS: R50_C4.pkl #frcnn_vgg16_coco.pkl #vgg16v2.pkl
  SOURCE_DATASETS: ('coco_2017_train',)
  TARGET_DATASETS: ('voc_2007_train','voc_2007_val','voc_2012_train') #subset of these, together 5392 imgs
  SCALES: (600,)
  MAX_SIZE: 900
  IMS_PER_BATCH: 2 #3 # two source, one target.
  BATCH_SIZE_PER_IM: 320
  SNAPSHOT_ITERS: 10000000 #NEVER
TEST:
  DATASETS: ('coco_2017_val',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .

INTERRUPTING: True
#THRESH_TIME: 2 days minus 15 mins from config.py

VOC_SUBSET: 'voc_subset.npy'  # 5392 imgs

#MODEL:
#  TYPE: generalized_rcnn
#  CONV_BODY: VGG16.add_VGG16_conv5_body
#  NUM_CLASSES: 81
#  FASTER_RCNN: True
#NUM_GPUS: 1
#SOLVER:
#  WEIGHT_DECAY: 0.0005
#  LR_POLICY: steps_with_decay
#  BASE_LR: 0.001
#  GAMMA: 0.1
#  MAX_ITER: 70000
#  WARM_UP_ITERS: 0
#  STEPS: [0, 50000]
#RPN:
#  SIZES: (128, 256, 512)
#FAST_RCNN:
#  ROI_BOX_HEAD: VGG16.add_VGG16_roi_fc_head
#TRAIN:
#  DOMAIN_ADAPTATION: True
#  DA_IMG_GRL_WEIGHT: 0.2
#  DA_INS_GRL_WEIGHT: 0.2
#  WEIGHTS: vgg16v2.pkl
#  SOURCE_DATASETS: ('coco_2017_val',)
#  TARGET_DATASETS: ('live_targets',)
#  SCALES: (800,)
#  MAX_SIZE: 1600
#  IMS_PER_BATCH: 2
#  BATCH_SIZE_PER_IM: 256
#  RPN_MIN_SIZE: 16
#TEST:
#  DATASETS: ('sim10k','cityscapes_car_val',)
#  SCALE: 800
#  MAX_SIZE: 1600
#  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
#  RPN_POST_NMS_TOP_N: 300
#  FORCE_JSON_DATASET_EVAL: True
#  RPN_MIN_SIZE: 16
#OUTPUT_DIR: .
#DATA_LOADER:
#  NUM_THREADS: 4
