MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG16.add_VGG16_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.002
  GAMMA: 0.1
  MAX_ITER: 35000
  WARM_UP_ITERS: 0
  STEPS: [0, 25000]
RPN:
  SIZES: (128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.add_VGG16_roi_fc_head
TRAIN:
  DOMAIN_ADAPTATION: True
  DA_IMG_GRL_WEIGHT: 0.2
  DA_INS_GRL_WEIGHT: 0.2
  WEIGHTS: vgg16v2.pkl
  SOURCE_DATASETS: ('coco_2017_val',)
  TARGET_DATASETS: ('live_targets',)
  SCALES: (800,)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 4
  BATCH_SIZE_PER_IM: 256
  RPN_MIN_SIZE: 16
TEST:
  DATASETS: ('sim10k','cityscapes_car_val',)
  SCALE: 800
  MAX_SIZE: 1600
  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
  RPN_POST_NMS_TOP_N: 300
  FORCE_JSON_DATASET_EVAL: True
  RPN_MIN_SIZE: 16
OUTPUT_DIR: .
DATA_LOADER:
  NUM_THREADS: 4
